/**
 * NRF NFManagement Service
 * NRF NFManagement Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.0.alpha-1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AccessType.h
 *
 *
 */

#ifndef AccessType_H_
#define AccessType_H_

#include "AccessType_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace nssf_server {
namespace model {

/// <summary>
///
/// </summary>
class AccessType {
 public:
  AccessType();
  virtual ~AccessType();

  void validate();

  bool operator==(const AccessType& rhs) const;
  bool operator!=(const AccessType& rhs) const;

  /////////////////////////////////////////////
  /// AccessType members

  AccessType_anyOf getValue() const;
  void setValue(AccessType_anyOf value);
  AccessType_anyOf::eAccessType_anyOf getEnumValue() const;
  void setEnumValue(AccessType_anyOf::eAccessType_anyOf value);

  friend void to_json(nlohmann::json& j, const AccessType& o);
  friend void from_json(const nlohmann::json& j, AccessType& o);

  friend void to_json(nlohmann::json& j, const AccessType_anyOf& o);
  friend void from_json(const nlohmann::json& j, AccessType_anyOf& o);

 protected:
  AccessType_anyOf m_value;
};

}  // namespace model
}  // namespace nssf_server
}  // namespace oai

#endif /* AccessType_H_ */
