---
{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.f1IPadd "/" .Values.multus.f1Netmask | nospace | quote }}
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net2
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.rruInterfaceIpadd "/" .Values.multus.rruInterfaceNetmask | nospace | quote }}
                }
        ]
      }
    }'
{{- end }}