version: '3.8'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./database/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    oai-nssf:
        container_name: "oai-nssf"
        image: oai-nssf:v1.4.0
        environment:
            - INSTANCE=0
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - NSSF_NAME=oai-nssf
            - NSSF_FQDN=nssf.oai-5gcn.eur
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - SBI_API_VERSION=v1
            - SBI_PORT_HTTP1=80
            - SBI_PORT_HTTP2=8080
            - NSSF_SLICE_CONFIG=/openair-nssf/etc/nssf_slice_config.yaml
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        volumes: 
            - ./nssf_slice_config.yaml:/openair-nssf/etc/nssf_slice_config.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai_udr:
        container_name: oai-udr
        image: oai-udr:v1.4.0
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - UDR_INTERFACE_NAME_FOR_NUDR=eth0
            - UDR_INTERFACE_PORT_FOR_NUDR=80
            - UDR_INTERFACE_HTTP2_PORT_FOR_NUDR=8080
            - UDR_API_VERSION=v1
            - MYSQL_IPV4_ADDRESS=192.168.70.131
            - MYSQL_USER=test
            - MYSQL_PASS=test
            - MYSQL_DB=oai_db
            - WAIT_MYSQL=120
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.70.133
    oai_udm:
        container_name: oai-udm
        image: oai-udm:v1.4.0
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - UDM_NAME=OAI_UDM
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - UDM_VERSION_NB=v1
            - USE_FQDN_DNS=yes
            - UDR_IP_ADDRESS=192.168.70.133
            - UDR_PORT=80
            - UDR_VERSION_NB=v1
            - UDR_FQDN=oai_udr
        depends_on:
            - oai_udr
        networks:
            public_net:
                ipv4_address: 192.168.70.134
    oai_ausf:
        container_name: oai-ausf
        image: oai-ausf:v1.4.0
        environment:
            - TZ=Europe/Paris
            - INSTANCE_ID=0
            - PID_DIR=/var/run
            - AUSF_NAME=OAI_AUSF
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - USE_FQDN_DNS=yes
            - UDM_IP_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_VERSION_NB=v1
            - UDM_FQDN=oai_udm
        depends_on:
            - oai_udm
        networks:
            public_net:
                ipv4_address: 192.168.70.135
    oai_nrf_slice12:
        container_name: oai-nrf-slice12
        image: oai-nrf:v1.4.0
        environment:
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            public_net:
                ipv4_address: 192.168.70.136
    oai_nrf_slice3:
        container_name: oai-nrf-slice3
        image: oai-nrf:v1.4.0
        environment:
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            public_net:
                ipv4_address: 192.168.70.137
    oai_amf:
        container_name: oai-amf
        image: oai-amf:v1.4.0
        environment:
            - TZ=Europe/paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            - SST_0=128
            - SD_0=128
            - SST_1=1
            - SD_1=0xFFFFFF
            - SST_2=130
            - SD_2=130
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai_smf_slice1
            - SMF_IPV4_ADDR_0=0.0.0.0
            - SMF_HTTP_VERSION_0=v1
            - SELECTED_0=true
            - SMF_INSTANCE_ID_1=2
            - SMF_FQDN_1=oai_smf_slice2
            - SMF_IPV4_ADDR_1=0.0.0.0
            - SMF_HTTP_VERSION_1=v1
            - SELECTED_1=false
            - MYSQL_SERVER=192.168.70.131
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - OPERATOR_KEY=63bfa50ee6523365ff14c1f45f88737d
            - NRF_IPV4_ADDRESS=0.0.0.0
            - NRF_PORT=80
            - EXTERNAL_NRF=no
            - NF_REGISTRATION=no
            - SMF_SELECTION=yes
            - USE_FQDN_DNS=yes
            - EXTERNAL_AUSF=yes
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            - AUSF_IPV4_ADDRESS=192.168.70.135
            - AUSF_PORT=80
            - AUSF_API_VERSION=v1
            - AUSF_FQDN=oai_ausf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=oai_udm
            - NRF_SELECTION=yes
            - EXTERNAL_NSSF=yes
            - NSSF_IPV4_ADDRESS=192.168.70.132
            - NSSF_PORT=80
            - NSSF_API_VERSION=v1
            - NSSF_FQDN=oai-nssf
            - USE_HTTP2=no
            - INT_ALGO_LIST=["NIA1" , "NIA2"]
            - CIPH_ALGO_LIST=["NEA1" , "NEA2"]
        depends_on:
            - mysql
            - oai_nrf_slice12
            - vpp_upf_slice3
            - oai_ausf
        networks:
            public_net:
                ipv4_address: 192.168.70.138
    oai_smf_slice1:
        container_name: oai-smf-slice1
        image: oai-smf:v1.4.0
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=oai_udm
            - UPF_IPV4_ADDRESS=127.0.0.1
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=yes
            - NSSAI_SST0=128
            - NSSAI_SD0=128
        depends_on:
            - oai_amf
            - oai_nrf_slice12
        networks:
            public_net:
                ipv4_address: 192.168.70.139
    oai_smf_slice2:
        container_name: oai-smf-slice2
        image: oai-smf:v1.4.0
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=0.0.0.0
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=yes
            - NSSAI_SST1=1
            - NSSAI_SD1=0
        depends_on:
            - oai_amf
            - oai_nrf_slice12
        networks:
            public_net:
                ipv4_address: 192.168.70.140
    oai_smf_slice3:
        container_name: oai-smf-slice3
        image: oai-smf:v1.4.0
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=0.0.0.0
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.137
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice3
            - USE_NETWORK_INSTANCE=yes
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=yes
            - NSSAI_SST1=130
            - NSSAI_SD1=130
        depends_on:
            - oai_amf
            - oai_nrf_slice3
        extra_hosts:
            - "vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.70.201"
        networks:
            public_net:
                ipv4_address: 192.168.70.141
    oai_spgwu_slice1:
        container_name: oai-spgwu-slice1
        image: oai-spgwu-tiny:v1.4.0
        environment:
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.2.1.0/24
            - BYPASS_UL_PFCP_RULES=no
            - MCC=208
            - MNC=95
            - MNC03=095
            - TAC=40960
            - GW_ID=1
            - REALM=openairinterface.org
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=oai_spgwu_slice1
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            - NSSAI_SST_0=128
            - NSSAI_SD_0=128
            - DNN_0=default
        depends_on:
            - oai_nrf_slice12
            - oai_smf_slice1
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.142
    oai_spgwu_slice2:
        container_name: oai-spgwu-slice2
        image: oai-spgwu-tiny:v1.4.0
        environment:
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.1.1.0/24
            - BYPASS_UL_PFCP_RULES=no
            - MCC=208
            - MNC=95
            - MNC03=095
            - TAC=40960
            - GW_ID=1
            - REALM=openairinterface.org
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=oai_spgwu_slice2
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            - NSSAI_SST_0=1
            - NSSAI_SD_0=0
            - DNN_0=oai
        depends_on:
            - oai_nrf_slice12
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.143
    vpp_upf_slice3:
        image: oai-upf-vpp:v1.4.0
        privileged: true
        container_name: vpp-upf-slice3
        environment:
            - IF_1_IP=192.168.70.201
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.72.201
            - IF_2_TYPE=N3
            - IF_2_NWI=access.oai.org
            - IF_3_IP=192.168.73.201
            - IF_3_TYPE=N6
            - IF_3_IP_REMOTE=192.168.73.145 # EXT-DN IP Address
            - IF_3_NWI=internet.oai.org
            - NAME=VPP-UPF
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/
            - SNSSAI_SD=130
            - SNSSAI_SST=130
            - DNN=oai.ipv4
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=192.168.70.137
            - NRF_PORT=8080
            - HTTP_VERSION=2
        depends_on:
            - oai_nrf_slice3
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.144
            public_net_access:
                ipv4_address: 192.168.72.144
            public_net_core:
                ipv4_address: 192.168.73.144
    oai_ext_dn:
        image: trf-gen-cn5g:latest
        privileged: true
        container_name: oai-ext-dn
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.2.1.2/32 via 192.168.70.142 dev eth0;"\
              "ip route add 12.1.1.129/32 via 192.168.70.143 dev eth0;"\
              "ip route add 12.1.1.2/32 via 192.168.73.201 dev eth1; sleep infinity"
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            public_net:
                ipv4_address: 192.168.70.145
            public_net_core:
                ipv4_address: 192.168.73.145
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core:
        name: oai-public-core
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core"
