apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    {{- include "oai-spgwu-tiny.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.pfcpServiceType }}
  {{- if eq .Values.service.pfcpServiceType "ClusterIP" }}
  clusterIP: None
  {{ end }}
  ports:
    - name: oai-spgwu-tiny
      # Port accessible outside cluster
      port: {{ .Values.service.pfcpPort }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.service.pfcpPort }}
      protocol: UDP
  selector:
    {{- include "oai-spgwu-tiny.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-gtpu-svc
  labels:
    {{- include "oai-spgwu-tiny.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.gtpuServiceType }} #LoadBalancer
  {{- if eq .Values.service.gtpuServiceType "ClusterIP" }}
  clusterIP: None
  {{ end }}
  ports:
    - name: s1u
      # Port accessible outside cluster
      port: {{ .Values.service.gtpuPort }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.service.gtpuPort }}
      protocol: UDP
  selector:
    {{- include "oai-spgwu-tiny.selectorLabels" . | nindent 4 }}
