#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
   name: oai-ran-base
spec:
  lookupPolicy:
    local: true
--- 
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  name: oai-ran-base
spec: 
  output: 
    to: 
      kind: ImageStreamTag
      name: "oai-ran-base:develop"
  runPolicy: Serial
  strategy:
    type: Docker
  source: 
    configMaps: 
      - configMap: 
          name: rhsm-conf
        destinationDir: rhsm-conf
      - configMap: 
          name: rhsm-ca
        destinationDir: rhsm-ca
    dockerfile: |
        FROM registry.access.redhat.com/ubi8/ubi:latest AS ran-base
        ARG NEEDED_GIT_PROXY
        ENV TZ=Europe/Paris
        ENV BUILD_UHD_FROM_SOURCE=True
        ENV UHD_VERSION=3.15.0.0
        # Copy the entitlements
        COPY ./etc-pki-entitlement /etc/pki/entitlement

        # Copy the subscription manager configurations
        COPY ./rhsm-conf /etc/rhsm
        COPY ./rhsm-ca /etc/rhsm/ca

        #install developers pkg/repo
        RUN rm -f /etc/rhsm-host && \
            yum repolist --disablerepo=* && \
            subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms && \
            yum update -y && \
            yum install -y \
               #gcc needed for build_oai
               gcc gcc-c++ \ 
               diffutils \
               file \
               psmisc \
               git \
               # python3-pip and pyyaml are used for conf template generation
               python3-pip \
               #unzip is needed for protobuf
               unzip && \
            pip3 install --ignore-installed pyyaml && \
            echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
            echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

        # In some network environments, GIT proxy is required
        RUN /bin/bash -c "if [[ -v NEEDED_GIT_PROXY ]]; then git config --global http.proxy $NEEDED_GIT_PROXY; fi"

        #create the WORKDIR
        RUN git clone -b develop https://gitlab.eurecom.fr/oai/openairinterface5g.git /oai-ran
        WORKDIR /oai-ran

        #run build_oai -I to get the builder image
        RUN /bin/sh oaienv && \ 
            cd cmake_targets && \
            mkdir -p log && \
            ./build_oai -I -w USRP && \
            rm /etc/pki/entitlement/*pem
    secrets: 
      - destinationDir: etc-pki-entitlement
        secret: 
          name: etc-pki-entitlement

